DROP TABLE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS FLIGHT;
drop TABLE IF EXISTS FLIGHTPROVIDER;
  
CREATE TABLE AIRPORT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CODE VARCHAR(50) NOT NULL
);

CREATE TABLE FLIGHTPROVIDER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE FLIGHTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  START VARCHAR(250) NOT NULL,
  STARTCODE INT NOT NULL,
  --foreign key (STARTCODE) references AIRPORT(ID),
  DESTINATION  VARCHAR(250) NOT NULL,
  DESTCODE INT NOT NULL,
  --foreign key (DESTCODE) references AIRPORT(ID),
  DEPARTURE VARCHAR(250) NOT NULL,
  ARRIVAL VARCHAR(250) NOT NULL,
  PROVIDER_ID INT NOT NULL,
  foreign key (PROVIDER_ID) references FLIGHTPROVIDER(ID),
  SEATS INT NOT NULL
);
